### ISSUE TITLE
On/Off switch not working any more

### ISSUE THREAD

**Issue by trex2000** [MrSleeps/Juwel-HeliaLux-Home-Assistant-Custom-Component#7]
Hello,
Thanks for making improvement to this integration.
With the last update the profile display works again.
However now i am facing another problem:
The on/off switch does not work anymore, if I switch it off, the lights remain off for almost a second and then it is switched on again.
The state of the switch continues to diaplay as off

**Comment by MrSleeps** [comment]
Fixed in v1.0.3, sometimes though the Juwel Controller does throw a wobbly and changes the values back (at least it does on mine). 

Something to note, for the light to be manually controlled you have to set manual simulation time, the maximum amount of time you can set that for is 24 hours and my controller will set it and then sometimes decides that's too long and resets it back to one hour.

Light status now updates every 15 seconds (was 1 minute previously)..

Let me know if this fixes it.

**Comment by trex2000** [comment]
Something is still not ok.
![image](https://github.com/user-attachments/assets/2cd6a61b-cd9c-4777-a5d1-affb429924f1)![image](https://github.com/user-attachments/assets/34a6f507-02d3-42f0-a8b2-61cf4af9c7ac)

If I have manual simulator enabled, toggling the switch sometimes remains in corect position (and does turn off the lights) but sometimes it just changes back after a couple of seconds, leaving the lights off. Sometimes it works correctly.
Maybe an idea would be to check the status by rereading the web page and only then change the state of the swith internally?
Another thing: 
The 2 flags![image](https://github.com/user-attachments/assets/1523da06-af41-4c86-91ec-75949a155830)
are read only, I cannot set them, only by the webif(That is integrated as a web page above the buttons from your integration)
Maybe they could be chaged to swith types and they should set manual override for an hour, for example.
Let me know if this helps, if not I can help you with testing.

**Comment by MrSleeps** [comment]
It's been running fine on mine since the last update i pushed. The controller itself sometimes resets things and everytime you manually visit the juwel controller website it takes over and seems to reset things, nothing I can do about that, its a bug/feature of the juwel website. You definitely on v1.0.3? 

For me to have a look what is going on you need to post the debug logs for the integration (settings->integrations->Juwel Helialux->Turn on debug logs, I can't even begin to look at what is going on from a picture when mine is working perfectly fine.

Also  if you want to do a PR to make the manualsimulation sensors into a switch, feel free to do so but tbh I can't see the point, the light handles all of that automatically.

**Comment by trex2000** [comment]
Also, if you make the profile setting to be changeable somehow then the turn on/off Switch can be left out as you can easily create a 'dark' profile that can be switched if needed.. Just an idea

**Comment by MrSleeps** [comment]
Just reread your post, did you say you have the juwel controller web interface embedded on home assistant? I'm confused by what you mean with:

"only by the webif(That is integrated as a web page above the buttons from your integration)"

**Comment by trex2000** [comment]
![image](https://github.com/user-attachments/assets/dcca9162-14a9-4d81-b3ac-6db232d3952d)


I have integrated the web page into home Assistant. But this was the issue, probably it was refreshing the web page as well and interfered with the juwel control integration.
I havr moved it to another dashboard and now it seems fine

**Comment by trex2000** [comment]
Also, ia there a possibility to change the profile? I don't know if writing the sensor's value will work, or it just displays the currently active profile?

**Comment by MrSleeps** [comment]
Yeah, its a weird thing on the controller website, when you open it up it takes control and does its own thing. Caused me a lot of issues (and wasted time) when I was trying to debug the light. You can graph the lights using one of the graphing cards in HA and the sensor information instead of pulling up the website.. 

I'll update the readme to mention that annoying feature of the controller!

**Comment by MrSleeps** [comment]
> Also, is there a possibility to change the profile? I don't know if writing the sensor's value will work, or it just displays the currently active profile?

I haven't actually looked into that, I imagine there is (it can be done via the controller website) but I don't have much free time at the moment to sit down and have a play..

**Comment by trex2000** [comment]
Hmm, it can be that because I loaded the web interface in HA as well it will reset the settings as it periodically reloads..
I will remove that and report back

**Comment by trex2000** [comment]
I also know some python but never developed a HA plugin. 
I will try to make some time and look into your code.
Anyway, thanks for the great work!! It's highly appreciated!
I am able now to control the aquarium lights to dim the room when the projector ia turned on.

**Comment by MrSleeps** [comment]
Yeah I'm learning as I go along, selecting a profile can be done (anything you can do via the website can be done via Home Assistant, its all just posting the correct data to the juwel controller). I'll see what I can do after work tonight.

Glad it's working for you!
